version: '3.8'
services:
  app:
    build: .
    container_name: todo-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todoapp
      - JWT_SECRET=secret_key
      - NODE_ENV=development
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes: 
      - .:/app
  db:
      image: postgres:13
      container_name: todo-db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=todoapp
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
      

